import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Map from '../components/Map'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Translink Map</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
          Vancouver Skytrain Stations
      </header>

      <subheader className={styles.subheader}>
          A web app that shows skytrain stops along the expo line.
      </subheader>

      <main className={styles.main}>
        <Map/>
      </main>

      <footer className={styles.footer}>
           © 2023 Alex Somerville 🗯️
      </footer>
    </div>
  )
}
